name: speakup_ai
description: "SpeakUp - AI-powered English speaking practice app."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.10.3 <4.0.0'
  flutter: '>=3.38.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  lottie: ^3.3.1
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_crashlytics: ^5.2.0
  firebase_analytics: ^12.3.0
  google_sign_in: ^7.2.0

  # State Management & Storage
  provider: ^6.1.5
  shared_preferences: ^2.5.4

  # AI & Networking
  http: ^1.6.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  uuid: ^4.3.3

  # UI & Animations
  google_fonts: ^8.0.2
  flutter_animate: ^4.5.2
  percent_indicator: ^4.2.5

  # Services & Utilities
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.2
  url_launcher: ^6.3.1
  intl: ^0.20.2


  # Environment & PDF
  flutter_dotenv: ^6.0.0
  file_picker: ^11.0.2
  syncfusion_flutter_pdf: ^33.1.49

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher_icon.png"
  web:
    generate: true
    image_path: "assets/launcher_icon.png"
  windows:
    generate: true
    image_path: "assets/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
