// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvSSCu7JrVypuidT7M_k-3nRy58kNNfA',
    appId: '1:278000782008:web:fd9fdff6ae08526f3a424d',
    messagingSenderId: '278000782008',
    projectId: 'speakup-5cafa',
    authDomain: 'speakup-5cafa.firebaseapp.com',
    storageBucket: 'speakup-5cafa.firebasestorage.app',
    measurementId: 'G-FYSVZP2QJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnjt7UbBXMVfU00SwS5F8zf1rxKnUbcw',
    appId: '1:278000782008:android:26747e3b637d95753a424d',
    messagingSenderId: '278000782008',
    projectId: 'speakup-5cafa',
    storageBucket: 'speakup-5cafa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-KlNZfr3CeTpkZ4ZEuS2vSKPZDxUmjlQ',
    appId: '1:278000782008:ios:7c356b7d1946b66a3a424d',
    messagingSenderId: '278000782008',
    projectId: 'speakup-5cafa',
    storageBucket: 'speakup-5cafa.firebasestorage.app',
    androidClientId: '278000782008-841g6mhicea46do9vlr2dqlmtl186aki.apps.googleusercontent.com',
    iosClientId: '278000782008-ulicjd0l22rk4042nr66dfjs6d4plf3v.apps.googleusercontent.com',
    iosBundleId: 'com.marwadiuniversity.speakup_ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-KlNZfr3CeTpkZ4ZEuS2vSKPZDxUmjlQ',
    appId: '1:278000782008:ios:7c356b7d1946b66a3a424d',
    messagingSenderId: '278000782008',
    projectId: 'speakup-5cafa',
    storageBucket: 'speakup-5cafa.firebasestorage.app',
    androidClientId: '278000782008-841g6mhicea46do9vlr2dqlmtl186aki.apps.googleusercontent.com',
    iosClientId: '278000782008-ulicjd0l22rk4042nr66dfjs6d4plf3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKvSSCu7JrVypuidT7M_k-3nRy58kNNfA',
    appId: '1:278000782008:web:bcefa78807c776553a424d',
    messagingSenderId: '278000782008',
    projectId: 'speakup-5cafa',
    authDomain: 'speakup-5cafa.firebaseapp.com',
    storageBucket: 'speakup-5cafa.firebasestorage.app',
    measurementId: 'G-4W4BQDC405',
  );
}
